dataset_name: thumos14
devices: [0, 1]
dataset:
  json_file: ./data/thumos14/annotations/thumos14.json
  feat_folder: ./data/thumos14/i3d_features
  num_classes: 20
  num_frames: 16
  input_dim: 2048
  max_input: 2304

model:
  win_size: 19
  freeze_bn: true
  freeze_bn_affine: true

training:
  batch_size: 8
  learning_rate: 1e-5
  weight_decay: 1e-3
  max_epoch: 40
  focal_loss: true

testing:
  conf_thresh: 0.01
  nms_thresh: 0.5
  nms_sigma: 0.5
  checkpoint_path: ./ckpt
  output_path: ./output